import java.util.ArrayList;

/**
 * Created by Holden on 12/02/2016. - COMPLETED
 *
 *
 *
 * Problem 12 - Highly Divisible Triangular Number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 *                  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *      10: 1,2,5,10
 *      15: 1,3,5,15
 *      21: 1,3,7,21
 *      28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */

public class Prob0012 {
    public static void main(String[] args) {
        long startTime = System.nanoTime();
        int answer = triangularNumber(500);
        long endTime = System.nanoTime();

        System.out.println(answer);

        long duration = (endTime - startTime);
        EulerTime.time(duration);
    }

    public static int triangularNumber(int upperBound) {
        int triangle = 1;
        int count = 1;
        int divisors = calculateDivisors(triangle);

        while (divisors <= upperBound) {
            count++;
            triangle += count;
            divisors = calculateDivisors(triangle);
        }

        return triangle;
    }

    private static int calculateDivisors(int number) {
        ArrayList<Integer> primes = EulerUtil.primeFactor(number);
        OccurrenceSet<Integer> primeSet = new OccurrenceSet<>();
        for (int prime: primes) {
            primeSet.add(prime);
        }

        int divisors = 1;
        for (int value: primeSet) {
            divisors *= (primeSet.get(value) + 1);
        }

        return divisors;
    }
}
