/**
 * Created by Holden on 11/19/2016. - COMPLETED
 *
 *
 *
 * Problem 2 - Even Fibonacci Numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class Prob0002 {
    public static void main(String[] args) {
        long startTime = System.nanoTime();
        int answer = evenFibonacciNumbers(4000000);
        long endTime = System.nanoTime();

        System.out.println(answer);

        long duration = (endTime - startTime);
        EulerTime.time(duration);
    }

    public static int evenFibonacciNumbers(int upperBound) {
        int fib1 = 1;
        int fib2 = 2;
        int temp;
        int fibSum = 0;

        while (fib2 < upperBound) {
            if (fib2 % 2 == 0) {
                fibSum += fib2;
            }
            temp = fib2;
            fib2 += fib1;
            fib1 = temp;
        }

        return fibSum;
    }
}
